### ISSUE TITLE
Problem in dataset

### ISSUE THREAD

**Issue by sanazmovahed** [Vanclief/go-crypto#1]
Hello Mr.Valencia
I'm Sanaz Movahed from Shahid Madani Azerbaijan university.
I've studied your article with title: Price Movement Prediction of Cryptocurrencies Using Sentiment Analysis and Machine Learning
I appreciate you for sharing your code and dataset. I want to implement your article solution, but I've faced with problems with reading .h5 files. Could you help me. 

#Here are some lines of my code:

dataset = h5py.File('bitcoin_tweets.h5')
list(dataset.keys())
grid = dataset['data']
grid.keys()
# the output:
         <KeysViewHDF5 ['axis0', 'axis1', 'block0_items', 'block0_values']>

print("axis0 data: {}".format(grid['block0_values']))
print("axis0 data attributes: {}".format(list(grid['block0_values'].attrs)))
Print("Unit: {}".format(grid['block0_values'].attrs['TITLE'].decode()))

# the output: 
         ValuesViewHDF5(<HDF5 group "/data" (4 members)>)
axis0 data: <HDF5 dataset "block0_values": shape (1391, 5), type "<f8">
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-9b6d4d40cc15> in <module>()
      
     print("axis0 data: {}".format(grid['block0_values']))
     print("axis0 data attributes: {}".format(list(grid['block0_values'].attrs.decode())))
     
      #print("Unit: {}".format(grid['block0_values'].attrs['TITLE'].decode()))

AttributeError: 'AttributeManager' object has no attribute 'decode'

As you can see, i got an error in the last line of code.
If you help me, I'll be glad.
thank you, in advance 

#Sanaz Movahed (GitHub account: @sanazmovahed)

**Comment by Vanclief** [comment]
Hello, 

This is a library for cryptography in Golang and completely unrelated to that project. If you have any issues with data please open them at the appropriate repository: https://github.com/Vanclief/algo-trading-crypto/issues. 

However I can't really help you with your code, I recommend you make this question over at stackoverflow.
